packages:
    - name: rso-invites
      functions:
        - name: invite
          runtime: nodejs:default
          source: .
          parameters:
            DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}