packages:
    - name: rso-iota-hook
      functions:
        - name: hook-controller
          runtime: python:default
          main: hook-controller.py
          parameters:
            DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
